title: Résumé
resume:
  name: Li Ma
  jobtitle: Network & Cybersecurity Engineer
  contact:
    - icon: fa-envelope
      text: i@imoe.ac.cn
    - icon: fa-phone-square
      text: +86-21-51016665 ext. 0
    - icon: fa-phone-square
      text: +1-616-319-3605
    - icon: fa-globe
      text: imoe.ac.cn
      link: https://www.imoe.ac.cn/
    - icon: fa-github
      text: hanyan-rst
      link: https://github.com/hanyan-rst
  education:
    - university: Shanghai Jian Qiao University, College of Information Technology
      duration: Oct 2022 - June 2024
      location: Shanghai, China
      major: B.Eng in Computer Science and Technology
    - university: Shanghai Polytechnic University, College of International Vocational Education
      duration: Sep 2020 - June 2022
      location: Shanghai, China
      major: Association Degree in Computer Network Technology
  skills:
    - title: Network & Security Devices
      items: Cisco, Mikrotik, Huawei, H3C, Fortigate, Sophos, Synology, Server.
    - title: Cloud Computing
      items: Linux, Windows Server, VMware Vsphere, Omnissa Horizon, Proxmox VE, Docker, AWS, Azure, Vultr, etc.
    - title: Network Implementing & Maintaining
      items: BGP, OSPF, RIP, Tunnel, SD-WAN, SDN, VPN, etc.
  experience:
    - title: Job Title 1
      duration: Apr 2016 - Now
      company: Your 1st, Inc.
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    - title: Job Title 2
      duration: Apr 2013 - Mar 2016
      company: Your 2nd, Inc.
      description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    - title: Job Title 3
      duration: Dec 2011 - Mar 2012
      company: Your 3rd Co, Ltd.
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  projects:
    - name: Project Name 1
      description: Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      contribution: Contributor.
    - name: Project Name 2
      description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      contribution: Creator and maintainer.
  languages:
    - name: English
      proficiency: Work proficiency
    - name: Mandarin Chinese
      proficiency: Native
