title: Résumé
resume:
  name: Li Ma
  jobtitle: Network & Cybersecurity Engineer
  contact:
    - icon: fa-envelope
      text: i@imoe.ac.cn
    - icon: fa-phone-square
      text: +86-21-51016665 ext. 0
    - icon: fa-phone-square
      text: +1-616-319-3605
    - icon: fa-globe
      text: imoe.ac.cn
      link: https://www.imoe.ac.cn/
    - icon: fa-github
      text: hanyan-rst
      link: https://github.com/hanyan-rst
  education:
    - university: Shanghai Jian Qiao University, College of Information Technology
      duration: Oct 2022 - June 2024
      location: Shanghai, China
      major: B.Eng in Computer Science and Technology
    - university: Shanghai Polytechnic University, College of International Vocational Education
      duration: Sep 2020 - June 2022
      location: Shanghai, China
      major: Association Degree in Computer Network Technology
  skills:
    - title: Network & Security Devices
      items: Cisco, Mikrotik, Huawei, H3C, Fortigate, Sophos, Synology, Server.
    - title: Cloud Computing
      items: Linux, Windows Server, VMware Vsphere, Omnissa Horizon, Proxmox VE, Docker, AWS, Azure, Vultr, etc.
    - title: Network Implementing & Maintaining
      items: BGP, OSPF, RIP, Tunnel, SD-WAN, SDN, VPN, etc.
  experience:
    - title: Information Technician, Network Information Center
      duration: July 2024 - Now
      company: Shanghai Commercial Accounting School
      description: 
    - title: Network Administrator & Information Technology Teacher (Intern)
      duration: June 2023  - July 2024
      company: Shanghai Caoyang No.2 High School
      description: Spearheaded school-wide digital transformation by orchestrating the integration of infrastructure resources, significantly optimizing system reliability and scalability. Architected and maintained robust campus network environments and mission-critical information systems. Beyond operations, engineered bespoke software solutions to automate IT curriculum support and administrative workflows. Provided core technical assurance for large-scale digital examinations and high-stakes online/offline events while leading advanced elective courses in CS and technological innovation.
    - title: Founder
      duration: Dec 2018 ‑ Aug 2021
      company: Shanghai Funxun Network Technology Co., Ltd.
      description: Collaborated with Shenzhen Mangning Data to architect global network acceleration services. Spearheaded in-depth analysis of mainland China’s ISP topologies and primary gateways to optimize routing paths for diverse service requirements. Engineered and maintained a high-performance 10Gbps SFP+/PON optical fiber infrastructure. Leveraged KVM virtualization and SD-WAN technologies to deliver scalable, multi-tenant network resources. Designed comprehensive cybersecurity frameworks and served as the primary responder for critical network security incidents, ensuring 24/7 environment integrity.
  projects:
    - name: A Robust Multi-Classification Algorithm Based on TabNet for Infrared Spectral Data of Chinese herbal medicine
      description: Infrared Physics and Technology
      contribution: Data visualization, Resources and Data curation during the research.
    - name: Project Name 2
      description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      contribution: Creator and maintainer.
  languages:
    - name: English
      proficiency: Work proficiency
    - name: Mandarin Chinese
      proficiency: Native
